DAY 1
CREATE TABLE emp
(
 empno decimal(4,0) NOT NULL,
 ename varchar(10) default NULL,
 job varchar(9) default NULL,
 mgr decimal(4,0) default NULL,
 hiredate date default NULL,
 sal decimal(7,2) default NULL,
 comm decimal(7,2) default NULL,
 deptno decimal(2,0) default NULL
);
CREATE TABLE dept (
 deptno decimal(2,0) default NULL,
 dname varchar(14) default NULL,
 loc varchar(13) default NULL
);
INSERT INTO emp VALUES
('7369','SMITH','CLERK','7902','1980-12-17','800.00',NULL,'20');
INSERT INTO emp VALUES
('7499','ALLEN','SALESMAN','7698','1981-02-20','1600.00','300.00','30');
INSERT INTO emp VALUES
('7521','WARD','SALESMAN','7698','1981-02-22','1250.00','500.00','30');
INSERT INTO emp VALUES
('7566','JONES','MANAGER','7839','1981-04-02','2975.00',NULL,'20');
INSERT INTO emp VALUES
('7654','MARTIN','SALESMAN','7698','1981-09-28','1250.00','1400.00','30');
INSERT INTO emp VALUES
('7698','BLAKE','MANAGER','7839','1981-05-01','2850.00',NULL,'30');
INSERT INTO emp VALUES
('7782','CLARK','MANAGER','7839','1981-06-09','2450.00',NULL,'10');
INSERT INTO emp VALUES
('7788','SCOTT','ANALYST','7566','1982-12-09','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7839','KING','PRESIDENT',NULL,'1981-11-17','5000.00',NULL,'10');
INSERT INTO emp VALUES
('7844','TURNER','SALESMAN','7698','1981-09-08','1500.00','0.00','30');
INSERT INTO emp VALUES
('7876','ADAMS','CLERK','7788','1983-01-12','1100.00',NULL,'20');
INSERT INTO emp VALUES
('7900','JAMES','CLERK','7698','1981-12-03','950.00',NULL,'30');
INSERT INTO emp VALUES
('7902','FORD','ANALYST','7566','1981-12-03','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7934','MILLER','CLERK','7782','1982-01-23','1300.00',NULL,'10');

INSERT INTO dept VALUES ('10','ACCOUNTING','NEW YORK');
INSERT INTO dept VALUES ('20','RESEARCH','DALLAS');
INSERT INTO dept VALUES ('30','SALES','CHICAGO');
INSERT INTO dept VALUES ('40','OPERATIONS','BOSTON');

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT ENAME,HIREDATE FROM EMP;
SELECT HIREDATE,HIREDATE FROM EMP;

SELECT COMM,SAL FROM EMP;

SELECT ENAME,SAL*12 FROM EMP;

SELECT SAL*6,SAL*12,SAL FROM EMP;

SELECT SAL*6, 0.1*SAL+SAL FROM EMP;

SELECT 0.7*SAL,1.7*SAL FROM EMP;

DAY 2
SELECT ENAME,SAL*12,0.7*SAL,SAL+500 FROM EMP;
SELECT ENAME AS "NAME",SAL*12 AS "ANNUAL SALARY",0.7*SAL AS "DECREMENTED SALARY",SAL+500 AS "BONUS SALARY" FROM EMP;
SELECT *,SAL*6 AS "HALF TERM SALARY",SAL*12 AS "FULL TERM SALARY" FROM EMP;
SELECT DISTINCT SAL FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT DISTINCT JOB, SAL FROM EMP;


SELECT ENAME,SAL FROM EMP WHERE SAL>3000;
SELECT * FROM EMP WHERE SAL*12>12000;
SELECT * FROM EMP WHERE HIREDATE>'1980-12-31';


SELECT ENAME AS "NAME",SAL*12 AS "ANNUAL SALARY" FROM EMP WHERE HIREDATE<'1987-01-01';
SELECT ENAME AS "EMPLOYEES NOT FROM DEPT.NO 30" FROM EMP WHERE DEPTNO!=30;
SELECT ENAME AS "EMPLOYEES NOT FROM DEPT.NO 30" FROM EMP WHERE DEPTNO<>30;


SELECT * FROM EMP WHERE JOB='SALESMAN' AND SAL>2000;
SELECT ENAME AS "NAME" FROM EMP WHERE JOB='MANAGER' AND SAL>2000 AND HIREDATE>'1980-12-31';
SELECT * FROM EMP WHERE HIREDATE>='1981-01-01' AND HIREDATE<='1981-12-31';
SELECT ENAME AS"NAME",SAL*6 AS"HALF TERM SALARY" FROM EMP WHERE SAL*12>8000 AND HIREDATE>='1981-12-31' AND HIREDATE<='1987-12-31';
SELECT * FROM EMP WHERE JOB='ANALYST' OR JOB='CLERK';
SELECT * FROM EMP WHERE SAL>2000 AND(JOB='CLERK' OR JOB='ANALYST');
SELECT ENAME AS "NAME" FROM EMP WHERE HIREDATE>'1978-12-31' AND HIREDATE<='1986-12-31' AND SAL>2000 AND (DEPTNO=10 OR DEPTNO=30) AND (JOB='CLERK' OR JOB='MANAGER' OR JOB='SALESMAN');
SELECT * FROM EMP WHERE NOT(JOB='SALESMAN');
SELECT * FROM EMP WHERE HIREDATE>='1981-01-01' AND HIREDATE<='1981-12-31' AND NOT(JOB='MANAGER'OR JOB='CLERK');

SELECT * FROM EMP WHERE JOB IN('MANAGER','PRESIDENT') AND SAL>2000 AND DEPTNO IN(20,30);
SELECT ENAME AS "NAME" , HIREDATE AS"HIRED DATE" FROM EMP WHERE DEPTNO IN(20,30) AND JOB NOT IN('CLERK','MANAGER')AND HIREDATE>'1982-12-31';
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 5000 AND (JOB='CLERK' OR JOB='MANAGER');
SELECT * FROM EMP WHERE HIREDATE BETWEEN '1977-01-01' AND '1987-12-31' AND SAL BETWEEN 3001 AND 5000;

SELECT * FROM EMP WHERE JOB='MANAGER' AND SAL NOT BETWEEN 1000 AND 3000;
SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP WHERE MGR IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;
SELECT * FROM EMP WHERE MGR IS NOT NULL AND (COMM IS NULL OR COMM=0) AND JOB IN ('MANAGER','SALESMAN');


SELECT * FROM EMP WHERE JOB LIKE '%MAN%';


DAY 3
SELECT MAX(ENAME) FROM EMP;
SELECT MIN(ENAME) FROM EMP;
SELECT MAX(HIREDATE) FROM EMP;
SELECT MIN(HIREDATE) FROM EMP;
SELECT COUNT(*) FROM EMP WHERE DEPTNO=20;
SELECT MAX(SAL),SUM(SAL) FROM EMP WHERE HIREDATE>'1980-12-31';
SELECT COUNT (DISTINCT SAL) FROM EMP;
SELECT AVG(SAL) FROM EMP WHERE SAL BETWEEN 1000 AND 3000 AND HIREDATE BETWEEN '1981-01-01' AND '1981-12-31';

SELECT COUNT(*) FROM EMP GROUP BY DEPTNO;
SELECT COUNT(*) FROM EMP GROUP BY DEPTNO;
SELECT COUNT(*),DEPTNO FROM EMP WHERE JOB='SALESMAN'GROUP BY DEPTNO;
SELECT MAX(SAL),JOB FROM EMP WHERE SAL>2000 AND JOB LIKE '%A%' GROUP BY JOB;
SELECT SAL FROM EMP GROUP BY SAL;
SELECT COUNT(*),SUM(SAL),DEPTNO FROM EMP WHERE MGR IS NOT NULL AND COMM IS NULL AND HIREDATE  BETWEEN '1982-01-01' AND '1982-12-31' GROUP BY DEPTNO;

SELECT COUNT(*),DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=2;
SELECT COUNT(*),DEPTNO FROM EMP WHERE SAL>1100 AND JOB='SALESMAN' GROUP BY DEPTNO HAVING MAX(SAL)>2000;
SELECT MAX(SAL),DEPTNO FROM EMP WHERE JOB IN('CLERK','MANAGER')GROUP BY DEPTNO HAVING MAX(SAL)>2000 AND MAX(SAL)<5000;
SELECT SAL FROM EMP GROUP BY SAL HAVING COUNT(SAL)>1;
SELECT AVG(SAL),DEPTNO FROM EMP WHERE JOB='MANAGER' AND SAL>2000 GROUP BY DEPTNO HAVING SUM(SAL)>3000;
SELECT * FROM EMP WHERE SAL>2000;

SELECT * FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH');
SELECT * FROM EMP WHERE HIREDATE>'1980-12-31' AND SAL<(SELECT SAL FROM EMP WHERE ENAME='JONES');
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='ALLEN') AND SAL>(SELECT SAL FROM EMP WHERE ENAME='JONES');
SELECT ENAME,HIREDATE FROM EMP WHERE ENAME LIKE '%S' AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='JAMES');
SELECT ENAME FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='JAMES')AND SAL>(SELECT SAL FROM EMP WHERE ENAME='ADAMS')AND JOB=(SELECT JOB FROM EMP WHERE ENAME='MILLER')AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MARTIN');
SELECT COUNT(*)FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH')AND SAL<(SELECT SAL FROM EMP WHERE ENAME='MARTIN');

SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');
SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='ALLEN');
SELECT * FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE SAL>3000) AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='BOSTON');
SELECT * FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='MILLER')AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');
SELECT COUNT(*) FROM EMP WHERE JOB='CLERK' AND DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH')AND SAL>(SELECT SAL FROM EMP WHERE ENAME='KING')AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MARTIN')AND DEPTNO= (SELECT DEPTNO FROM DEPT WHERE LOC='BOSTON');

DAY 4
SELECT E1.SAL FROM EMP E1 WHERE 4-1 IN (SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL<E2.SAL);
SELECT E1.SAL FROM EMP E1 WHERE 10-1 IN (SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL>E2.SAL);
SELECT LOC FROM DEPT WHERE DEPTNO IN(SELECT E1.DEPTNO FROM EMP E1 WHERE 7 IN (SELECT COUNT (DISTINCT E2.SAL)FROM EMP E2 WHERE E1.SAL<E2.SAL));
SELECT * FROM EMP E1 WHERE (SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL<E2.SAL) IN (2,3);
SELECT * FROM EMP E1 WHERE (SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL<E2.SAL) BETWEEN 0 AND 4;
SELECT MAX(SAL),DEPTNO FROM EMP GROUP BY DEPTNO;
SELECT MAX(E1.SAL),DEPTNO FROM EMP E1 WHERE SAL<(SELECT MAX(E2.SAL)FROM EMP E2 WHERE E1.DEPTNO=E2.DEPTNO)GROUP BY E1.DEPTNO;
SELECT * FROM EMP E1 WHERE SAL>(SELECT AVG(E2.SAL) FROM EMP E2 WHERE E1.DEPTNO=E2.DEPTNO);


SELECT * FROM EMP CROSS JOIN DEPT;
SELECT * FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE SAL>2000;
SELECT DNAME,ENAME,SAL FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE LOC='NEW YORK' AND SAL>ALL(SELECT SAL FROM EMP WHERE JOB='CLERK') ;
SELECT dept.dname,dept.loc,dept.deptno,emp.sal,emp.ename FROM emp INNER JOIN dept ON emp.deptno=dept.deptno WHERE emp.deptno=20 AND emp.sal>ALL (SELECT sal FROM emp WHERE hiredate>ALL (SELECT hiredate FROM emp WHERE deptno IN (SELECT deptno FROM dept WHERE loc='CHICAGO')));
SELECT * FROM emp INNER JOIN dept ON emp.deptno=dept.deptno WHERE hiredate>ANY(SELECT hiredate FROM emp 
WHERE job='CLERK') AND dept.dname='ACCOUNTING' AND emp.mgr IS NOT NULL;

SELECT E1.ename,E2.ename FROM emp E1 JOIN emp E2 ON E1.mgr=E2.empno;

SELECT E1.ename,E1.hiredate,E2.ename FROM emp E1 JOIN emp E2 ON E1.mgr=E2.empno WHERE E1.sal>E2.sal AND E2.hiredate>'1980-12-31';
SELECT E1.ename,E1.sal*12,E2.ename,E2.sal*12 FROM emp E1 JOIN emp E2 ON E1.mgr=E2.empno WHERE E1.job=E2.job AND E2.sal>ALL(SELECT sal FROM emp WHERE ename='%A%');
SELECT E1.ename,E2.ename,E3.ename FROM emp E1 JOIN emp E2 ON E1.mgr=E2.empno JOIN emp E3 ON E2.mgr=E3.empno;
SELECT E1.ename,E2.ename,E3.ename FROM emp E1 JOIN emp E2 ON E1.mgr=E2.empno JOIN emp E3 ON E2.mgr=E3.empno 
WHERE E1.sal>(SELECT sal FROM emp WHERE ename='ALLEN') AND E2.hiredate>E3.hiredate AND E1.job=E2.job 
AND E2.deptno=(SELECT deptno FROM dept WHERE loc='NEW YORK');

SELECT E1.ename,E2.ename,E3.ename,D1.dname,D2.dname,D3.dname FROM emp E1 JOIN emp E2 ON E1.mgr=E2.empno 
JOIN emp E3 ON E2.mgr=E3.empno JOIN dept D1 ON E1.deptno=D1.deptno JOIN dept D2 ON E2.deptno=D2.deptno 
JOIN dept D3 ON E3.deptno=D3.deptno;

 SELECT D1.loc FROM emp E1 JOIN emp E2 ON E1.mgr=E2.empno 
JOIN emp E3 ON E2.mgr=E3.empno JOIN dept D1 ON E1.deptno=D1.deptno JOIN dept D2 ON E2.deptno=D2.deptno 
JOIN dept D3 ON E3.deptno=D3.deptno WHERE E1.job='SALESMAN';
SELECT * FROM EMP WHERE (SAL*6)>8000;
