DAY 1
CREATE TABLE emp
(
 empno decimal(4,0) NOT NULL,
 ename varchar(10) default NULL,
 job varchar(9) default NULL,
 mgr decimal(4,0) default NULL,
 hiredate date default NULL,
 sal decimal(7,2) default NULL,
 comm decimal(7,2) default NULL,
 deptno decimal(2,0) default NULL
);
CREATE TABLE dept (
 deptno decimal(2,0) default NULL,
 dname varchar(14) default NULL,
 loc varchar(13) default NULL
);
INSERT INTO emp VALUES
('7369','SMITH','CLERK','7902','1980-12-17','800.00',NULL,'20');
INSERT INTO emp VALUES
('7499','ALLEN','SALESMAN','7698','1981-02-20','1600.00','300.00','30');
INSERT INTO emp VALUES
('7521','WARD','SALESMAN','7698','1981-02-22','1250.00','500.00','30');
INSERT INTO emp VALUES
('7566','JONES','MANAGER','7839','1981-04-02','2975.00',NULL,'20');
INSERT INTO emp VALUES
('7654','MARTIN','SALESMAN','7698','1981-09-28','1250.00','1400.00','30');
INSERT INTO emp VALUES
('7698','BLAKE','MANAGER','7839','1981-05-01','2850.00',NULL,'30');
INSERT INTO emp VALUES
('7782','CLARK','MANAGER','7839','1981-06-09','2450.00',NULL,'10');
INSERT INTO emp VALUES
('7788','SCOTT','ANALYST','7566','1982-12-09','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7839','KING','PRESIDENT',NULL,'1981-11-17','5000.00',NULL,'10');
INSERT INTO emp VALUES
('7844','TURNER','SALESMAN','7698','1981-09-08','1500.00','0.00','30');
INSERT INTO emp VALUES
('7876','ADAMS','CLERK','7788','1983-01-12','1100.00',NULL,'20');
INSERT INTO emp VALUES
('7900','JAMES','CLERK','7698','1981-12-03','950.00',NULL,'30');
INSERT INTO emp VALUES
('7902','FORD','ANALYST','7566','1981-12-03','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7934','MILLER','CLERK','7782','1982-01-23','1300.00',NULL,'10');

INSERT INTO dept VALUES ('10','ACCOUNTING','NEW YORK');
INSERT INTO dept VALUES ('20','RESEARCH','DALLAS');
INSERT INTO dept VALUES ('30','SALES','CHICAGO');
INSERT INTO dept VALUES ('40','OPERATIONS','BOSTON');

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT ENAME,HIREDATE FROM EMP;
SELECT HIREDATE,HIREDATE FROM EMP;

SELECT COMM,SAL FROM EMP;

SELECT ENAME,SAL*12 FROM EMP;

SELECT SAL*6,SAL*12,SAL FROM EMP;

SELECT SAL*6, 0.1*SAL+SAL FROM EMP;

SELECT 0.7*SAL,1.7*SAL FROM EMP;

DAY 2
SELECT ENAME,SAL*12,0.7*SAL,SAL+500 FROM EMP;
SELECT ENAME AS "NAME",SAL*12 AS "ANNUAL SALARY",0.7*SAL AS "DECREMENTED SALARY",SAL+500 AS "BONUS SALARY" FROM EMP;
SELECT *,SAL*6 AS "HALF TERM SALARY",SAL*12 AS "FULL TERM SALARY" FROM EMP;
SELECT DISTINCT SAL FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT DISTINCT JOB, SAL FROM EMP;


SELECT ENAME,SAL FROM EMP WHERE SAL>3000;
SELECT * FROM EMP WHERE SAL*12>12000;
SELECT * FROM EMP WHERE HIREDATE>'1980-12-31';


SELECT ENAME AS "NAME",SAL*12 AS "ANNUAL SALARY" FROM EMP WHERE HIREDATE<'1987-01-01';
SELECT ENAME AS "EMPLOYEES NOT FROM DEPT.NO 30" FROM EMP WHERE DEPTNO!=30;
SELECT ENAME AS "EMPLOYEES NOT FROM DEPT.NO 30" FROM EMP WHERE DEPTNO<>30;


SELECT * FROM EMP WHERE JOB='SALESMAN' AND SAL>2000;
SELECT ENAME AS "NAME" FROM EMP WHERE JOB='MANAGER' AND SAL>2000 AND HIREDATE>'1980-12-31';
SELECT * FROM EMP WHERE HIREDATE>='1981-01-01' AND HIREDATE<='1981-12-31';
SELECT ENAME AS"NAME",SAL*6 AS"HALF TERM SALARY" FROM EMP WHERE SAL*12>8000 AND HIREDATE>='1981-12-31' AND HIREDATE<='1987-12-31';
SELECT * FROM EMP WHERE JOB='ANALYST' OR JOB='CLERK';
SELECT * FROM EMP WHERE SAL>2000 AND(JOB='CLERK' OR JOB='ANALYST');
SELECT ENAME AS "NAME" FROM EMP WHERE HIREDATE>'1978-12-31' AND HIREDATE<='1986-12-31' AND SAL>2000 AND (DEPTNO=10 OR DEPTNO=30) AND (JOB='CLERK' OR JOB='MANAGER' OR JOB='SALESMAN');
SELECT * FROM EMP WHERE NOT(JOB='SALESMAN');
SELECT * FROM EMP WHERE HIREDATE>='1981-01-01' AND HIREDATE<='1981-12-31' AND NOT(JOB='MANAGER'OR JOB='CLERK');

SELECT * FROM EMP WHERE JOB IN('MANAGER','PRESIDENT') AND SAL>2000 AND DEPTNO IN(20,30);
SELECT ENAME AS "NAME" , HIREDATE AS"HIRED DATE" FROM EMP WHERE DEPTNO IN(20,30) AND JOB NOT IN('CLERK','MANAGER')AND HIREDATE>'1982-12-31';
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 5000 AND (JOB='CLERK' OR JOB='MANAGER');
SELECT * FROM EMP WHERE HIREDATE BETWEEN '1977-01-01' AND '1987-12-31' AND SAL BETWEEN 3001 AND 5000;

SELECT * FROM EMP WHERE JOB='MANAGER' AND SAL NOT BETWEEN 1000 AND 3000;
SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP WHERE MGR IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;
SELECT * FROM EMP WHERE MGR IS NOT NULL AND (COMM IS NULL OR COMM=0) AND JOB IN ('MANAGER','SALESMAN');


SELECT * FROM EMP WHERE JOB LIKE '%MAN%';


DAY 3
SELECT MAX(ENAME) FROM EMP;
SELECT MIN(ENAME) FROM EMP;
SELECT MAX(HIREDATE) FROM EMP;
SELECT MIN(HIREDATE) FROM EMP;
SELECT COUNT(*) FROM EMP WHERE DEPTNO=20;
SELECT MAX(SAL),SUM(SAL) FROM EMP WHERE HIREDATE>'1980-12-31';
SELECT COUNT (DISTINCT SAL) FROM EMP;
SELECT AVG(SAL) FROM EMP WHERE SAL BETWEEN 1000 AND 3000 AND HIREDATE BETWEEN '1981-01-01' AND '1981-12-31';

SELECT COUNT(*) FROM EMP GROUP BY DEPTNO;
SELECT COUNT(*) FROM EMP GROUP BY DEPTNO;
SELECT COUNT(*),DEPTNO FROM EMP WHERE JOB='SALESMAN'GROUP BY DEPTNO;
SELECT MAX(SAL),JOB FROM EMP WHERE SAL>2000 AND JOB LIKE '%A%' GROUP BY JOB;
SELECT SAL FROM EMP GROUP BY SAL;
SELECT COUNT(*),SUM(SAL),DEPTNO FROM EMP WHERE MGR IS NOT NULL AND COMM IS NULL AND HIREDATE  BETWEEN '1982-01-01' AND '1982-12-31' GROUP BY DEPTNO;

SELECT COUNT(*),DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=2;
SELECT COUNT(*),DEPTNO FROM EMP WHERE SAL>1100 AND JOB='SALESMAN' GROUP BY DEPTNO HAVING MAX(SAL)>2000;
SELECT MAX(SAL),DEPTNO FROM EMP WHERE JOB IN('CLERK','MANAGER')GROUP BY DEPTNO HAVING MAX(SAL)>2000 AND MAX(SAL)<5000;
SELECT SAL FROM EMP GROUP BY SAL HAVING COUNT(SAL)>1;
SELECT AVG(SAL),DEPTNO FROM EMP WHERE JOB='MANAGER' AND SAL>2000 GROUP BY DEPTNO HAVING SUM(SAL)>3000;
SELECT * FROM EMP WHERE SAL>2000;

SELECT * FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH');
SELECT * FROM EMP WHERE HIREDATE>'1980-12-31' AND SAL<(SELECT SAL FROM EMP WHERE ENAME='JONES');
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='ALLEN') AND SAL>(SELECT SAL FROM EMP WHERE ENAME='JONES');
SELECT ENAME,HIREDATE FROM EMP WHERE ENAME LIKE '%S' AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='JAMES');
SELECT ENAME FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='JAMES')AND SAL>(SELECT SAL FROM EMP WHERE ENAME='ADAMS')AND JOB=(SELECT JOB FROM EMP WHERE ENAME='MILLER')AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MARTIN');
SELECT COUNT(*)FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH')AND SAL<(SELECT SAL FROM EMP WHERE ENAME='MARTIN');

SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');
SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='ALLEN');
SELECT * FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE SAL>3000) AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='BOSTON');
SELECT * FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='MILLER')AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');
SELECT COUNT(*) FROM EMP WHERE JOB='CLERK' AND DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH')AND SAL>(SELECT SAL FROM EMP WHERE ENAME='KING')AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MARTIN')AND DEPTNO= (SELECT DEPTNO FROM DEPT WHERE LOC='BOSTON');

SELECT DNAME FROM DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE JOB='CLERK');
SELECT * FROM EMP WHERE SAL=(SELECT MAX(SAL)FROM EMP);
SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL)FROM EMP);
SELECT MAX(SAL) FROM EMP WHERE SAL<(SELECT MAX(SAL)FROM EMP WHERE SAL<(SELECT MAX(SAL)FROM EMP));
SELECT MIN(SAL) FROM EMP WHERE SAL>(SELECT MIN(SAL)FROM EMP);
SELECT * FROM emp WHERE sal=(SELECT MIN(sal) FROM emp WHERE sal>(SELECT MIN(sal) FROM emp WHERE sal>(SELECT MIN(sal) FROM emp)));
SELECT loc from dept WHERE deptno IN (SELECT deptno FROM emp WHERE sal=(SELECT MAX(sal) FROM emp 
WHERE sal<(SELECT MAX(sal) FROM emp)));
SELECT * FROM emp WHERE sal > ALL(SELECT sal FROM emp WHERE job='CLERK');
SELECT * FROM emp WHERE sal > ANY(SELECT sal FROM emp WHERE job='CLERK');
SELECT * FROM emp WHERE sal > ALL(SELECT sal FROM emp WHERE job='SALESMAN')AND sal < ANY(SELECT sal FROM emp WHERE job='PRESIDENT');
SELECT * FROM emp  WHERE hiredate>ALL(SELECT hiredate FROM emp WHERE deptno IN (SELECT deptno FROM dept WHERE loc='NEW YORK')) AND sal>(SELECT sal FROM emp WHERE ename='%A%' OR ename='%s%');
SELECT * FROM emp WHERE empno=(SELECT mgr FROM emp WHERE ename='SMITH'); 
SELECT * FROM emp WHERE empno=(SELECT mgr FROM emp WHERE empno=(SELECT mgr FROM emp WHERE ename='WARD'));
SELECT * FROM emp WHERE mgr IN (SELECT empno FROM emp WHERE empno IN (SELECT mgr FROM emp WHERE ename='JONES'));
SELECT * FROM emp WHERE MGR IN (SELECT mgr FROM emp WHERE ename = 'JONES');
SELECT * FROM EMP WHERE MGR IN (SELECT empno FROM emp WHERE empno IN (SELECT mgr FROM emp WHERE empno IN (SELECT mgr FROM emp WHERE ename = 'WARD')));
SELECT * FROM emp WHERE MGR IN (SELECT mgr FROM emp WHERE empno IN(SELECT mgr FROM emp WHERE ename='WARD'));





